[package]
name = "native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
serde_serialize = []

[dependencies]
prost = "0.11"
prost-types = "0.11"
prost-wkt = "0.4"
prost-wkt-types = "0.4"
serde = { version = "1.0", features = ["derive"] }
tonic = "0.9"
uuid = { version = "1.1", features = ["v4", "fast-rng", "macro-diagnostics"]}

[build-dependencies]
tonic = "0.9"
tonic-build = "0.9"
prost-build = "0.11"
prost-wkt-build = "0.4"
